### ISSUE TITLE
Webtool Returns 502 Bad Gateway/Desktop vr. 1.02 returns SentenceParserBridge Error

### ISSUE THREAD

**Issue by magiccactus221** [memphis-iis/cohmetrix-issues#110]
Hello,

Recently I have been unable to access the cohmetrix web tool, the cohmetrix.memphis.edu address returns a 502 Bad Gateway error. Additionally the desktop version (1.02, build 9) returns the following error when I attempt to run analysis on my text corpus:

ERROR: -Popularte text- SentenceParserBridge
   at SentenceParserBridge.SPB.Run(String command, String args) in C:\Users\awind\OneDrive\Desktop\Workspace\CohMetrixCore\SentenceParserBridge\SentenceParserBridge.cs:line 35
   at MPCharniak.Charniak.start() in C:\Users\awind\OneDrive\Desktop\Workspace\CohMetrixCore\MPCharniak\Charniak.cs:line 98
   at MPCharniak.Charniak.parse(String sentence) in C:\Users\awind\OneDrive\Desktop\Workspace\CohMetrixCore\MPCharniak\Charniak.cs:line 146
   at MPCharniak.Charniak.parse2(String[] sentences) in C:\Users\awind\OneDrive\Desktop\Workspace\CohMetrixCore\MPCharniak\Charniak.cs:line 167
   at MPCharniak.MPParser.parse(String[] sentences) in C:\Users\awind\OneDrive\Desktop\Workspace\CohMetrixCore\MPCharniak\MPParser.cs:line 46
   at MPCohMetrix.CohMetrix.GetTextRep(String text) in C:\Users\awind\OneDrive\Desktop\Workspace\CohMetrixCore\MPCohMetrix\CohMetrix.cs:line 1054
   at MPCohMetrix.CohMetrix.AnalyzeTextForWeb(String text) in C:\Users\awind\OneDrive\Desktop\Workspace\CohMetrixCore\MPCohMetrix\CohMetrix.cs:line 181

Any advice/resolution is appreciated.

**Comment by JRustyHaner** [comment]
@magiccactus221 love the name by the way.

Please download this version, I had forgotten to add the parser to the release. The web version is available as well. The University shuts down our instances sometimes, so thank you for letting us know to restart it.

https://github.com/memphis-iis/cohmetrix-issues/raw/refs/heads/main/cohmetrixcorecli-1.0.9.1-windows-installer.exe

**Comment by magiccactus221** [comment]
Bad news, downloaded the CLI version you linked and it crashes back to desktop very quickly. I can make out a vague error message about "please update to the latest version of cohmetrix" but it disappears before I can read the error with any certainty.

Advice appreciated, sorry for the headaches.

Edit: also webpage is still showing a 502 bad gateway error.
