### ISSUE TITLE
Error, no results

### ISSUE THREAD

**Issue by lisabean** [memphis-iis/cohmetrix-issues#2]
Hi, when I run the program on just one single text file, this is the progress + error that shows: 
Welcome to CohMetrix Core 1.0 [Build 9]
Please select input and output folder and press analyze to start processing. Threads (amount of files processed at the same time) can be set below to speed up processing.
Number of threads available: 16
Warning: using many threads might slow down your computer. Coh-Metrix is set to use 1 threads.
Input folder: C:\Users\lisac\sciebo\Uni\Dissertation\Coh-Metrix\CM_data
Output folder: C:\Users\lisac\sciebo\Uni\Dissertation\Coh-Metrix
Initializing CohMetrix...
Starting: LN_23_Jannis.txt Thread: 6
Reading: C:\Users\lisac\sciebo\Uni\Dissertation\Coh-Metrix\CM_data\LN_23_Jannis.txt Thread: 6
Started: LN_23_Jannis.txt Thread: 6
ERROR: -Data construtor- MPCohMetrix
   at MPCohMetrix.DataConstructor1.ConvertZtoP(Double z) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 378
   at MPCohMetrix.DataConstructor1.AddLinearCombinationToTableFromFile(DataSet ds, DataTable table, XmlNode formulaNode, String columnName) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 362
   at MPCohMetrix.DataConstructor1.AddIndexToTable(DataSet ds, DataTable table, XmlNode indexNode) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 322
   at MPCohMetrix.DataConstructor1.AddGroupToTable(DataSet ds, DataTable table, XmlNode groupNode) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 286
   at MPCohMetrix.DataConstructor1.GetTable(DataSet ds, XmlDocument doc) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 212
   at MPCohMetrix.DataConstructor1.GetDataSet(DataSet ds) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 143
   at MPCohMetrix.CohMetrix.AnalyzeTextForWeb(String text) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\CohMetrix.cs:line 210

**Comment by JRustyHaner** [comment]
The data constructor is usually an error that comes up when there is a problem with the corpus or the location of the dataset cohmetrix uses. Could you send me an email with the corpus so I can test it?

**Comment by JRustyHaner** [comment]
@lisabean this error was troubleshooted by running the corpus. We will mark it as closed. Please reopen if the problem happens again.
