### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by penarroj** [memphis-iis/cohmetrix-issues#44]
Name: Manuel Rodríguez
Email: penarroj@uji.es
Institution: Universitat Jaume I (Spain)
Secret Key: 660 (secret) Build 4
Description of your research: the analysis of writte output by English as a foreign language learners.

Note: I've asked for the license 2 days ago, but when entering it today the secret key provided by the software was different.

Thanks again in advance and sorry for the inconvenience.

**Comment by JRustyHaner** [comment]
@penarroj The license is tied to a specific key found on your computer. If you changed computers or hardware then it will have to be re licensed.

**Comment by JRustyHaner** [comment]
@penarroj I sent you a new license

**Comment by penarroj** [comment]
Dear James, 

Thanks for the (re)-license. The software starts now but it does not end the analysis of just 4 txt files (300 words each) txt (UTF-8). There's a new window asking the user to "please update to the latest version of CohMetric Core". I downloaded and installed version 1.0.2 since it is supossed to be the last one. Could you please help? I attach a word.doc with a visual of what I'm describing in case it helps.
[Cohmetrix bug.docx](https://github.com/memphis-iis/cohmetrix-issues/files/14040974/Cohmetrix.bug.docx)

**Comment by JRustyHaner** [comment]
@JRustyHaner Inside the install folder there is a version.txt, it should read 4,cohmetrix-issues. If it doesn't, please copy that in and save it. Then restart cohmetrix.

**Comment by penarroj** [comment]
I've solved the version issue, thanks :) . Now, it still does not work properly since the analysis is not completed. I've noticed an error spotted by the application (I copy paste from the application dialogue box):

Welcome to CohMetrix Core 1.0  (Build 4)
Please select input and output folder and press analyze to start processing. Threads (amount of files processed at the same time) can be set below to speed up processing.
Number of threads available: 8
Warning: using many threads might slow down your computer. Coh-Metrix is set to use 1 threads.
Input folder: C:\Users\epime\OneDrive\Escritorio\prueba 2 con plain text codificación windows
Output folder: C:\Users\epime\OneDrive\Escritorio\Coh-metrix output
Initializing CohMetrix...
Starting: Aida t1.txt Thread: 14
Reading: C:\Users\epime\OneDrive\Escritorio\prueba 2 con plain text codificación windows\Aida t1.txt Thread: 14
Started: Aida t1.txt Thread: 14
**ERROR: -Data construtor- MPCohMetrix**
   at MPCohMetrix.DataConstructor1.ConvertZtoP(Double z) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 388
   at MPCohMetrix.DataConstructor1.AddLinearCombinationToTableFromFile(DataSet ds, DataTable table, XmlNode formulaNode, String columnName) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 374
   at MPCohMetrix.DataConstructor1.AddIndexToTable(DataSet ds, DataTable table, XmlNode indexNode) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 326
   at MPCohMetrix.DataConstructor1.AddGroupToTable(DataSet ds, DataTable table, XmlNode groupNode) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 290
   at MPCohMetrix.DataConstructor1.GetTable(DataSet ds, XmlDocument doc) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 217
   at MPCohMetrix.DataConstructor1.GetDataSet(DataSet ds) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 147
   at MPCohMetrix.CohMetrix.AnalyzeTextForWeb(String text) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\CohMetrix.cs:line 218

thanks in advance, again.
Manuel

**Comment by JRustyHaner** [comment]
@JRustyHaner could you email the T1.txt to me at jrhaner@memphis.edui?

**Comment by penarroj** [comment]
sent

**Comment by JRustyHaner** [comment]
@penarroj I sent you the output with instructions to fix. It seems like you need to use the uninstaller and delete the cohmetrix folder and install again. Please report back if you have any more issues.

**Comment by penarroj** [comment]
@JRustyHaner I've deleted everything, restarted the computer, and reinstalled the software following every single step: i)updating version file, ii) delete "data" folder so it reinstalls and updates automatically. The problem persists, however. It starts the analysis but it never ends, same error. I copy paste:

Welcome to CohMetrix Core 1.0  (Build 2)
Please select input and output folder and press analyze to start processing. Threads (amount of files processed at the same time) can be set below to speed up processing.
Number of threads available: 8
Warning: using many threads might slow down your computer. Coh-Metrix is set to use 1 threads.
Input folder: C:\Users\epime\OneDrive\Escritorio\coh-metrix input
Output folder: C:\Users\epime\OneDrive\Escritorio\coh metrix output
Initializing CohMetrix...
Starting: T1.txt Thread: 13
Reading: C:\Users\epime\OneDrive\Escritorio\coh-metrix input\T1.txt Thread: 13
Started: T1.txt Thread: 13
**ERROR: -Data construtor- MPCohMetrix**
   at MPCohMetrix.DataConstructor1.ConvertZtoP(Double z) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 388
   at MPCohMetrix.DataConstructor1.AddLinearCombinationToT

I've installed CohMetrixCore in another computer as there must be something wrong with the one I'm using. Could you please send me a new license key for issue 679 (secret) Build 4? Just to check it is the computer and not the software.

Kind regards and thanks again,

Manuel Rodríguez Peñarroja

**Comment by JRustyHaner** [comment]
@penarroj 

According to your output, you are using build 2, which is not the current version.

**Comment by penarroj** [comment]
@JRustyHaner 
 Same happens with build 4:

Welcome to CohMetrix Core 1.0  (Build 4)
Please select input and output folder and press analyze to start processing. Threads (amount of files processed at the same time) can be set below to speed up processing.
Number of threads available: 8
Warning: using many threads might slow down your computer. Coh-Metrix is set to use 1 threads.
Input folder: C:\Program Files (x86)\CohMetrixCore\cohmetrix input
Output folder: C:\Program Files (x86)\CohMetrixCore\cohmetrix output
Combine CSVs: True
Initializing CohMetrix...
Starting: T1.txt Thread: 13
Reading: C:\Program Files (x86)\CohMetrixCore\cohmetrix input\T1.txt Thread: 13
Started: T1.txt Thread: 13
**ERROR: -Data construtor- MPCohMetrix**
   at MPCohMetrix.DataConstructor1.ConvertZtoP(Double z) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 388
   at MPCohMetrix.DataConstructor1.AddLinearCombinationToTableFromFile(DataSet ds, DataTable table, XmlNode formulaNode, String columnName) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 374
   at MPCohMetrix.DataConstructor1.AddIndexToTable(DataSet ds, DataTable table, XmlNode indexNode) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 326
   at MPCohMetrix.DataConstructor1.AddGroupToTable(DataSet ds, DataTable table, XmlNode groupNode) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 290
   at MPCohMetrix.DataConstructor1.GetTable(DataSet ds, XmlDocument doc) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 217
   at MPCohMetrix.DataConstructor1.GetDataSet(DataSet ds) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 147
   at MPCohMetrix.CohMetrix.AnalyzeTextForWeb(String text) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\CohMetrix.cs:line 218

**Comment by JRustyHaner** [comment]
@penarroj Sorry for the late response. I hate to ask, but do you have another PC available you can replicate the process on?

**Comment by penarroj** [comment]
@JRustyHaner no need to apologise :). Thanks a lot for helping out with this.  I do have an Dell computer (now I use a Huawei) but I need a new password. I just copy paste from two comments ago:

"I've installed CohMetrixCore in another computer as there must be something wrong with the one I'm using. Could you please send me a new license key for issue 679 (secret) Build 4? Just to check it is the computer and not the software."

Regards,
Manuel Rodríguez

**Comment by JRustyHaner** [comment]
@penarroj a license has been emailed to you! Thanks.
