### ISSUE TITLE
Issues running on Windows 11 Pro

### ISSUE THREAD

**Issue by contemmcm** [memphis-iis/cohmetrix-issues#59]
I am trying to run cohmetrix on a single file directory, but I am getting the following error:

```
Welcome to CohMetrix Core 1.0  (Build 3)
Please select input and output folder and press analyze to start processing. Threads (amount of files processed at the same time) can be set below to speed up processing.
Number of threads available: 32
Warning: using many threads might slow down your computer. Coh-Metrix is set to use 1 threads.
Input folder: C:\Users\muril\OneDrive\Documentos\Corpus
Output folder: C:\Users\muril\Videos
Initializing CohMetrix...
Starting: doc1.txt Thread: 14
Reading: C:\Users\muril\OneDrive\Documentos\Corpus\doc1.txt Thread: 14
Started: doc1.txt Thread: 14
ERROR: -Data construtor- MPCohMetrix
   at MPCohMetrix.DataConstructor1.ConvertZtoP(Double z) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 388
   at MPCohMetrix.DataConstructor1.AddLinearCombinationToTableFromFile(DataSet ds, DataTable table, XmlNode formulaNode, String columnName) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 374
   at MPCohMetrix.DataConstructor1.AddIndexToTable(DataSet ds, DataTable table, XmlNode indexNode) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 326
   at MPCohMetrix.DataConstructor1.AddGroupToTable(DataSet ds, DataTable table, XmlNode groupNode) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 290
   at MPCohMetrix.DataConstructor1.GetTable(DataSet ds, XmlDocument doc) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 217
   at MPCohMetrix.DataConstructor1.GetDataSet(DataSet ds) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\DataConstructor1.cs:line 147
   at MPCohMetrix.CohMetrix.AnalyzeTextForWeb(String text) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\CohMetrix.cs:line 218
```

Can somebody help on this?

Thanks!

**Comment by JRustyHaner** [comment]
@contemmcm please send the document that you are trying to run to jrhaner@memphis.edu
