### ISSUE TITLE
CohmetrixCLI crashes to desktop after attempting to download data

### ISSUE THREAD

**Issue by magiccactus221** [memphis-iis/cohmetrix-issues#83]
Issue is basically title. Running windows 10 pro build 19045.4291.
CohMetrix CLI build: 6 (downloaded from the download page)
Both .NET core 7 and ASP .NET core 7 runtime are installed.

Have attempted to run Cohmetrix as admin to see if that fixes the issue, issue persists.

Following is error log from command line:

Coh-Metrix Core CLI Build 6
University of Memphis: Institute for Intelligent Systems
This is not the latest version of Coh-Metrix Core. Please update to the latest version.
Downloading model data...
Data downloaded from  http://cohmetrix-new.memphis.edu/api/downloadData
Data downloaded from http://cohmetrix.memphis.edu/api/downloadData
Could not download data from http://localhost:3000/api/downloadData . Trying next URL.
Unhandled exception. System.Exception: Could not download data from any URL. Please check your internet connection and try again.
   at CohMetrixCoreCLI.Program.<>c__DisplayClass15_0.<<Main>b__1>d.MoveNext() in C:\Users\Rusty\Desktop\CohMetrixCore\CohMetrixCoreCLI\Program.cs:line 99
--- End of stack trace from previous location ---
   at CohMetrixCoreCLI.Program.Main(String[] args) in C:\Users\Rusty\Desktop\CohMetrixCore\CohMetrixCoreCLI\Program.cs:line 82

Happy to respond to further questions, thanks for assistance. I use cohmetrix daily as part of my research workflow so access is important.

**Comment by JRustyHaner** [comment]
@magiccactus221 Have you tried running it as an administrator?

**Comment by magiccactus221** [comment]
I mentioned this in the body of the original post, but I have tried running cohmetrix as administrator and nothing changes. Still get a crash to desktop with the same error message. I have also tried adding an exception for cohmetrix to my firewall in case it might be getting a connection block, no change.

**Comment by JRustyHaner** [comment]
@magiccactus221  Please check in C:\Users\USERNAME\AppData\Local for a folder called CohMetrixCore. It should contain a data folder that has folders like LM, a config.txt, etc. If it does't have those, delete the entire CohMetrixCore folder and run it again.

**Comment by magiccactus221** [comment]
I checked and those folders are indeed missing. I will delete the CohMetrixCore folder and run again and follow up once I have done so.

**Comment by JRustyHaner** [comment]
@magiccactus221 please run it as administrator

**Comment by magiccactus221** [comment]
Good news is it stopped crashing to desktop. Bad news is it's now hanging indefinitely at the downloading data step. I can see the data folder has been created in the /USERNAME/appdata/Local/CohMetrixCore directory but the size is staying at zero.

**Comment by magiccactus221** [comment]
It looks like it's now having problems grabbing the lisence key. After unzipping the contents of the data folder into the target directory, I'm greeted with a new error message and another crash to desktop, copied below:

Trying License Server:  http://cohmetrix-new.memphis.edu/api/getDesktopKey
Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\CohMetrixCoreCLI\license.txt' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at IISLicensing.IISLicenseManager.registerKey(String key) in C:\Users\Rusty\Desktop\CohMetrixCore\IISLicensing\Class1.cs:line 146
   at CohMetrixCoreCLI.Program.Main(String[] args) in C:\Users\Rusty\Desktop\CohMetrixCore\CohMetrixCoreCLI\Program.cs:line 152

Interestingly if I run as administrator the above error message does not appear however I just get booted back to desktop with no error message showing.

**Comment by JRustyHaner** [comment]
@magiccactus221 It looks like you do not have access to :\Program Files (x86)\CohMetrixCoreCLI\license.txt.  You may have to delete that file, and run cohmetrix as administrator.

**Comment by magiccactus221** [comment]
Deleted the file, running as administrator and now cohmetrix just immediately crashes to desktop with no error message. Screen flashes for a second and back to desktop.

**Comment by magiccactus221** [comment]
I'll give a clean install a go and let you know if that fixes the issue. Thanks very much for your patience.

**Comment by JRustyHaner** [comment]
@magiccactus221 the web version is accessible at cohmetrix.memphis.edu, please update your links.
